#!/usr/bin/env python3
from __future__ import annotations

import argparse
import html
import json
from pathlib import Path

STYLE = "\n".join(
    [
        ":root { color-scheme: dark; }",
        (
            "body { margin: 0; font-family: Inter, ui-sans-serif, system-ui, "
            '-apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; '
            "background: #121212; color: rgba(255,255,255,0.87); }"
        ),
        "main { max-width: 1120px; margin: 0 auto; padding: 40px 20px 72px; }",
        "a { color: #69F0AE; }",
        (
            ".kpis { display: grid; grid-template-columns: repeat(auto-fit, "
            "minmax(160px, 1fr)); gap: 12px; margin: 24px 0; }"
        ),
        (
            ".kpi, .card { background: #1D1D1D; border: 1px solid "
            "rgba(255,255,255,0.1); border-radius: 8px; padding: 16px; }"
        ),
        ".kpi strong { display: block; font-size: 28px; color: #69F0AE; }",
        "table { width: 100%; border-collapse: collapse; margin-top: 18px; }",
        (
            "th, td { border-bottom: 1px solid rgba(255,255,255,0.1); "
            "padding: 10px 8px; text-align: left; vertical-align: top; }"
        ),
        "th { color: #03DAC6; font-weight: 650; }",
        ".status-passed { color: #00E676; font-weight: 700; }",
        ".status-failed { color: #FF5252; font-weight: 700; }",
        ".muted { color: rgba(255,255,255,0.62); }",
    ]
)


def write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def artifact_links(item: dict, slug: str, key: str) -> str:
    links = []
    for filename in item[key]:
        url = f"results/{slug}/{html.escape(filename)}"
        links.append(f'<a href="{url}">{html.escape(filename)}</a>')
    return "<br>".join(links) if links else '<span class="muted">none</span>'


def build(results_dir: Path, site_dir: Path) -> None:
    manifest_path = results_dir / "manifest.json"
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    passed = int(manifest["passed_count"])
    failed = int(manifest["failed_count"])
    rows = []
    for item in manifest["notebooks"]:
        slug = item["slug"]
        status_class = f"status-{html.escape(item['status'])}"
        rows.append(
            "<tr>"
            f"<td>{html.escape(item['notebook'])}</td>"
            f'<td class="{status_class}">{html.escape(item["status"])}</td>'
            f"<td>{item['elapsed_seconds']}</td>"
            f"<td>{artifact_links(item, slug, 'json_files')}</td>"
            f"<td>{artifact_links(item, slug, 'html_files')}</td>"
            f"<td>{artifact_links(item, slug, 'csv_files')}</td>"
            f'<td><a href="results/{html.escape(item["test_result"])}">test_result.json</a></td>'
            f'<td><a href="results/{slug}/stdout.txt">stdout</a></td>'
            "</tr>"
        )

    safety_line = (
        "Deterministic offline research run from Webull-style OHLCV sample data. "
        "live Webull trading calls: none."
    )
    output_links = (
        '<a href="results/manifest.json">manifest.json</a> | '
        '<a href="results/notebook-test-results.json">notebook-test-results.json</a> | '
        '<a href="results-summary.json">results-summary.json</a>'
    )
    table_head = (
        "<thead><tr><th>Notebook</th><th>Status</th><th>Seconds</th>"
        "<th>JSON</th><th>Charts</th><th>CSV</th><th>Test Result</th><th>Log</th></tr></thead>"
    )

    research_html = f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Webull Quantopian-Style Results</title>
  <style>{STYLE}</style>
</head>
<body>
  <main>
    <p><a href="../index.html">Home</a></p>
    <h1>Webull Quantopian-Style Results</h1>
    <p class="muted">{safety_line}</p>
    <section class="kpis">
      <div class="kpi"><span>notebooks</span><strong>{manifest["notebook_count"]}</strong></div>
      <div class="kpi"><span>passed</span><strong>{passed}</strong></div>
      <div class="kpi"><span>failed</span><strong>{failed}</strong></div>
    </section>
    <section class="card">
      <h2>Run Outputs</h2>
      <p>{output_links}</p>
      <table>
        {table_head}
        <tbody>{''.join(rows)}</tbody>
      </table>
    </section>
  </main>
</body>
</html>
"""

    home_html = f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Webull OpenAPI Thai Lab</title>
  <style>{STYLE}</style>
</head>
<body>
  <main>
    <h1>Webull OpenAPI Thai Lab</h1>
    <p class="muted">Static research outputs generated by GitHub Actions.</p>
    <section class="card">
      <h2>Quantopian-Style Research Results</h2>
      <p>{passed} notebooks passed, {failed} notebooks failed.</p>
      <p><a href="quantopian-style/index.html">Open results dashboard</a></p>
    </section>
  </main>
</body>
</html>
"""

    summary = {
        "name": manifest["name"],
        "live_mode": manifest["live_mode"],
        "notebook_count": manifest["notebook_count"],
        "passed_count": passed,
        "failed_count": failed,
        "notebooks": [
            {
                "notebook": item["notebook"],
                "slug": item["slug"],
                "status": item["status"],
                "json_files": item["json_files"],
                "html_files": item["html_files"],
                "csv_files": item["csv_files"],
                "test_result": item["test_result"],
                "code_cell_count": item["code_cell_count"],
            }
            for item in manifest["notebooks"]
        ],
    }

    write(site_dir / "index.html", home_html)
    write(site_dir / "quantopian-style" / "index.html", research_html)
    write(
        site_dir / "quantopian-style" / "results-summary.json",
        json.dumps(summary, indent=2, sort_keys=True) + "\n",
    )
    print(f"Wrote dashboard to {site_dir}")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Build static dashboard for Quantopian-style results."
    )
    parser.add_argument("--results-dir", default="site/quantopian-style/results")
    parser.add_argument("--site-dir", default="site")
    args = parser.parse_args()
    build(Path(args.results_dir), Path(args.site_dir))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
